### ISSUE TITLE
Live updating

### ISSUE THREAD

**Issue by greatislander** [everywhereschool/everywhereschool#14]

**Comment by Nealevf** [comment]
I want to make sure I'm looking in the right place. I opened the dev site shortly before streams were supposed to go live. My expectation was that they would switch to live status when their start time arrived. They did not. Was that what I should have been looking for?

**Comment by greatislander** [comment]
Did you look at the link in the pull request? https://deploy-preview-23--everywhereschool.netlify.com/

**Comment by Nealevf** [comment]
ah, I see it now. I'll leave that site open for the next few hours and see how it works.
