### ISSUE TITLE
Day title repeating bug

### ISSUE THREAD

**Issue by Nealevf** [everywhereschool/everywhereschool#16]
The "Tomorrow’s Livestreams" and "Coming Later" titles are being repeated for every event that's tomorrow.

<img width="1409" alt="Screen Shot 2020-04-04 at 9 44 12 AM" src="https://user-images.githubusercontent.com/7558069/78452439-403b0c80-7659-11ea-8812-e753d5072c97.png">

**Comment by greatislander** [comment]
Fixed in 302d501.
