### ISSUE TITLE
Improve submission form

### ISSUE THREAD

**Issue by Nealevf** [everywhereschool/everywhereschool#19]
- Separate submission form from streams table
- Add a note field
- Add back in a photo field
- Ask for timezone
- change email to go to hello@everywhereschool.live address

**Comment by greatislander** [comment]
@Nealevf I would love to set this up using Netlify Forms (https://www.netlify.com/products/forms/). Then we could style and integrate the form directly into the site which would be pretty cool.

**Comment by Nealevf** [comment]
Hmm. While Netlify's forms certainly look easy to implement, it's also a relatively small win. Airtable's forms are doing their job, and submissions are coming in. Let's think about it.
